In [14]:
import pandas as pd
import matplotlib as plt
import numpy as np
from pathlib import Path
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

In [2]:
train_df = pd.read_csv(Path('Resources/2019loans.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'))

In [18]:
train_df.head(10)

,Unnamed: 0,index,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,57107,57107,13375.0,0.1797,483.34,MORTGAGE,223000.0,Not Verified,low_risk,n,...,100.0,50.0,0.0,0.0,577150.0,122018.0,32000.0,170200.0,N,N
1,141451,141451,21000.0,0.1308,478.68,MORTGAGE,123000.0,Source Verified,low_risk,n,...,85.0,33.3,0.0,0.0,132750.0,27896.0,15900.0,35398.0,N,N
2,321143,321143,20000.0,0.1240,448.95,MORTGAGE,197000.0,Source Verified,low_risk,n,...,85.7,33.3,0.0,0.0,628160.0,114043.0,22600.0,90340.0,N,N
3,11778,11778,3000.0,0.1240,100.22,RENT,45000.0,Not Verified,low_risk,n,...,100.0,16.7,1.0,0.0,42006.0,20761.0,19900.0,15406.0,N,N
4,169382,169382,30000.0,0.1612,1056.49,MORTGAGE,133000.0,Source Verified,low_risk,n,...,100.0,66.7,0.0,0.0,283248.0,109056.0,79500.0,58778.0,N,N
5,31295,31295,6500.0,0.1614,228.98,MORTGAGE,65000.0,Not Verified,low_risk,n,...,92.3,50.0,1.0,0.0,64660.0,39487.0,12800.0,42060.0,N,N
6,173238,173238,40000.0,0.1240,897.89,MORTGAGE,171000.0,Not Verified,low_risk,n,...,88.9,75.0,0.0,0.0,772030.0,83509.0,41200.0,81300.0,N,N
7,116755,116755,5000.0,0.1719,178.74,MORTGAGE,55000.0,Not Verified,low_risk,n,...,90.0,0.0,0.0,0.0,17075.0,11244.0,500.0,14275.0,N,N
8,170311,170311,6000.0,0.1102,196.49,OWN,36000.0,Not Verified,low_risk,n,...,100.0,0.0,1.0,0.0,65200.0,21103.0,43300.0,12100.0,N,N
9,254794,254794,10625.0,0.1102,347.95,RENT,73000.0,Source Verified,low_risk,n,...,91.9,30.0,0.0,0.0,41869.0,11859.0,24500.0,10169.0,N,N

In [19]:
y_train = train_df["loan_status"]
X_train = train_df.drop(columns = ["loan_status"])
X_train = pd.get_dummies(X_train)
X_train.head(10)

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,...,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N,debt_settlement_flag_Y
0,57107,57107,13375.0,0.1797,483.34,223000.0,29.99,0.0,0.0,15.0,...,0,1,0,1,1,0,1,0,1,0
1,141451,141451,21000.0,0.1308,478.68,123000.0,11.26,2.0,0.0,16.0,...,0,1,0,1,1,0,1,0,1,0
2,321143,321143,20000.0,0.1240,448.95,197000.0,11.28,0.0,0.0,12.0,...,0,1,0,1,1,0,1,0,1,0
3,11778,11778,3000.0,0.1240,100.22,45000.0,18.08,0.0,0.0,12.0,...,0,1,0,1,1,0,1,0,1,0
4,169382,169382,30000.0,0.1612,1056.49,133000.0,27.77,0.0,2.0,13.0,...,0,1,0,1,1,0,1,0,1,0
5,31295,31295,6500.0,0.1614,228.98,65000.0,27.49,1.0,0.0,9.0,...,0,1,0,1,1,0,1,0,1,0
6,173238,173238,40000.0,0.1240,897.89,171000.0,20.74,0.0,0.0,9.0,...,0,1,0,1,1,0,1,0,1,0
7,116755,116755,5000.0,0.1719,178.74,55000.0,10.80,1.0,0.0,5.0,...,0,1,0,1,1,0,1,0,1,0
8,170311,170311,6000.0,0.1102,196.49,36000.0,27.28,0.0,0.0,19.0,...,0,1,0,1,1,0,1,0,1,0
9,254794,254794,10625.0,0.1102,347.95,73000.0,7.09,0.0,2.0,18.0,...,0,1,0,1,1,0,1,0,1,0

In [20]:
y_test = test_df["loan_status"]
X_test = test_df.drop(columns = ["loan_status"])
X_test = pd.get_dummies(X_test)
X_test.head(10)

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,...,verification_status_Source Verified,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N
0,67991,67991,40000.0,0.0819,814.70,140000.0,19.75,0.0,1.0,18.0,...,0,0,1,0,1,1,0,1,0,1
1,25429,25429,6000.0,0.1524,208.70,55000.0,11.52,2.0,0.0,8.0,...,0,0,1,0,1,1,0,1,0,1
2,38496,38496,3600.0,0.1695,128.27,42000.0,6.74,0.0,0.0,6.0,...,0,0,1,0,1,1,0,1,0,1
3,19667,19667,20000.0,0.1524,478.33,100000.0,12.13,0.0,2.0,7.0,...,0,0,1,0,1,1,0,1,0,1
4,37505,37505,3600.0,0.1240,120.27,50000.0,16.08,0.0,3.0,6.0,...,0,0,1,0,1,1,0,1,0,1
5,26517,26517,27000.0,0.0819,549.93,57000.0,31.41,0.0,0.0,18.0,...,0,1,1,0,1,0,1,1,0,1
6,30063,30063,15000.0,0.0881,310.00,50000.0,24.44,0.0,1.0,9.0,...,0,0,1,0,1,1,0,1,0,1
7,31659,31659,19000.0,0.0881,602.52,70000.0,30.94,0.0,0.0,19.0,...,0,0,1,0,1,0,1,1,0,1
8,15003,15003,27575.0,0.1171,912.07,142000.0,17.90,0.0,0.0,20.0,...,1,0,1,0,1,1,0,1,0,1
9,75464,75464,31500.0,0.1774,795.45,100000.0,25.05,2.0,1.0,17.0,...,1,0,1,0,1,1,0,1,0,1

In [21]:
y_test = test_df["loan_status"]
X_test = test_df.drop(columns = ["loan_status"])
X_test = pd.get_dummies(X_test)
X_test.head(10)

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,...,verification_status_Source Verified,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N
0,67991,67991,40000.0,0.0819,814.70,140000.0,19.75,0.0,1.0,18.0,...,0,0,1,0,1,1,0,1,0,1
1,25429,25429,6000.0,0.1524,208.70,55000.0,11.52,2.0,0.0,8.0,...,0,0,1,0,1,1,0,1,0,1
2,38496,38496,3600.0,0.1695,128.27,42000.0,6.74,0.0,0.0,6.0,...,0,0,1,0,1,1,0,1,0,1
3,19667,19667,20000.0,0.1524,478.33,100000.0,12.13,0.0,2.0,7.0,...,0,0,1,0,1,1,0,1,0,1
4,37505,37505,3600.0,0.1240,120.27,50000.0,16.08,0.0,3.0,6.0,...,0,0,1,0,1,1,0,1,0,1
5,26517,26517,27000.0,0.0819,549.93,57000.0,31.41,0.0,0.0,18.0,...,0,1,1,0,1,0,1,1,0,1
6,30063,30063,15000.0,0.0881,310.00,50000.0,24.44,0.0,1.0,9.0,...,0,0,1,0,1,1,0,1,0,1
7,31659,31659,19000.0,0.0881,602.52,70000.0,30.94,0.0,0.0,19.0,...,0,0,1,0,1,0,1,1,0,1
8,15003,15003,27575.0,0.1171,912.07,142000.0,17.90,0.0,0.0,20.0,...,1,0,1,0,1,1,0,1,0,1
9,75464,75464,31500.0,0.1774,795.45,100000.0,25.05,2.0,1.0,17.0,...,1,0,1,0,1,1,0,1,0,1

In [7]:
for column in X_train.columns:
    if column not in X_test.columns:
        X_test[column] = 0

In [8]:
reg = LogisticRegression().fit(X_train, y_train)
reg.score(X_test, y_test)

C:\Users\zachg\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.5253083794130158

In [9]:
randomForestClass = RandomForestClassifier(random_state=0)
randomForestClass.fit(X_train, y_train)
print("RandomForestClassifier score: ", randomForestClass.score(X_test,y_test))

RandomForestClassifier score:  0.6146320714589536

In [10]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
logisticRegr_scaled = LogisticRegression(
    solver='lbfgs',
    max_iter=100,
    random_state=0
)
logisticRegr_scaled.fit(X_train_scaled, y_train)
print("LogisticRegressin scaled score: ", logisticRegr_scaled.score(X_test_scaled, y_test))

LogisticRegressin scaled score:  0.7201190982560612

C:\Users\zachg\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [12]:
randomForestClass_scaled = RandomForestClassifier(random_state=0)
randomForestClass_scaled.fit(X_train_scaled, y_train)
print("RandomForestClassifier scaled score: ", randomForestClass_scaled.score(X_test_scaled, y_test))

RandomForestClassifier scaled score:  0.6150574223734581